name: train
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Add missing GPG keys
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA16FCBCA621E701
          # Add other keys as needed

      - name: Set up Python 3.8
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get install -y python3.8
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
          sudo update-alternatives --set python3 /usr/bin/python3.8
          python --version
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install azureml-core
        run: |
          pip install azureml-core
      - name: train_pipeline
        env:
          # get all information
          # az ad sp create-for-rbac --sdk-auth --name ml-auth 
          # repo_token: ${{ secrets.GITHUB_TOKEN }}
          
          AZUREML_CLIENTID: ${{secrets.AZUREML_CLIENTID}}
          AZUREML_TENANTID: ${{secrets.AZUREML_TENANTID}}
          AZUREML_SECRET: ${{secrets.AZUREML_SECRET}}
          AZUREML_SUBSCRIPTION: ${{secrets.AZUREML_SUBSCRIPTION}}
          AZUREML_RESOURCE_GROUP: ${{secrets.AZUREML_RESOURCE_GROUP}}
          AZUREML_WORKSPACE: ${{secrets.AZUREML_WORKSPACE}}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python iris_train_pipeline.py
          # echo "supervised learning output"
          # cat output.txt